# Generated by Django 6.1.1 on 2026-10-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
        migrations.AlterModelTable(
            name='revision',
            table='note_revision',
        ),
    ]
